% Script to setup and run event_doppler

dc = event_doppler('wav_file',...
        fullfile('..', 'reference', 'charvat_doppler', 'Off of Newton Exit 17.wav'), ...
    'debug_level', 1, ...
    'oversample_factor', 4, ...
    'dwell_period_ms', 50, ...
    'n_detection_dwell', 5, ...
    'windowing_function', 'taylor', ...
    'channel_vector', 2);




